'use strict'
angular = require 'angular'
d3 = require 'd3'
app = angular.module 'mainApp', [require 'angular-material']
	# charts
	.directive 'cumChart', require './components/charts/cumChart'
	.directive 'arrChart', require './components/charts/arrChart'
	.directive 'mainDer', require './components/charts/main'
	.directive 'startDer', require './components/charts/start'
	.directive 'costDer', require './components/charts/cost'
	# directives
	.directive 'shifter' , require './directives/shifter'
	.directive 'horAxisDer', require './directives/xAxis'
	.directive 'verAxisDer', require './directives/yAxis'
	.directive 'shifter' , require './directives/shifter'
	.directive 'behavior', require './directives/behavior'
	.directive 'datum', require './directives/datum'
	.directive 'd3Der', require './directives/d3Der'
	# .directive 'changeChart', require './components/changes/changeChart'
	# .directive 'changeDer', require './components/changes/changes2'